---
# - name: Activate sources
#   copy:
#     dest: /etc/apt/sources.list
#     content: |
#       deb http://archive.ubuntu.com/ubuntu xenial main restricted universe

- name: Install OpenSlides Dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python3-reportlab
  - python3-setuptools
  - python3-whoosh
  - python3-pip
  - redis-server

# TODO: Install and configure postgresql

- name: Install nginx
  when: openslides_nginx_domains or openslides_nginx_global
  become: yes
  register: nginxInstalled
  apt:
    name: nginx
    state: present

- name: Stop and disable nginx, it will be configured later
  when: nginxInstalled.changed and (openslides_nginx_domains or openslides_nginx_global)
  service:
    name: nginx.service
    state: stopped
    enabled: no

- name: Install git and development tools
  when: openslides_use_git
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - npm

- name: Create a symlink from nodejs to node
  when: openslides_use_git
  become: yes
  file:
    state: link
    path: /usr/bin/node
    src: /usr/bin/nodejs

- set_fact:
    pip_executable: pip3
    openslides_distro_fround: true
    openslides_bin: /usr/local/bin/openslides
    daphne_bin: /usr/local/bin/daphne
